# Generated by Django 5.1.6 on 2025-03-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Artist', 'Artist'), ('Client', 'Client')], max_length=10),
        ),
    ]
