# Generated by Django 5.1.7 on 2025-04-09 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_user_id_cart_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='cart_item',
            old_name='user',
            new_name='user_id',
        ),
    ]
