# Generated by Django 5.1.7 on 2025-04-07 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderart',
            name='art_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='orderart',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
